### PR TITLE
Added Jenkins scripts

### PR DESCRIPTION
**Pull request by rasolca**
Added scripts needed by Jenkins to test on `daint`

### CODE REVIEW

**Comment by rasolca** [comment]
Run tests

**Comment by rasolca** [comment]
Run tests

**Comment by jenkssl** [comment]
No test results found.

**Comment by rasolca** [comment]
Run tests

**Comment by jenkssl** [comment]
No test results found.

**Comment by rasolca** [comment]
Run tests

**Comment by jenkssl** [comment]
No test results found.

**Comment by rasolca** [comment]
Run tests

**Comment by jenkssl** [comment]
Run tests

**Pull request merged**
