### PR TITLE
CMake Refactoring and updates

### PR DESCRIPTION
**Pull request by albestro**
In this PR I'm trying to clean a bit the cmake scripts.

General:
- [ ] ~License from DLAF -> DLAI~ (this is going to be addressed in the documentation PR)
- [x] Adapt scripts from DLAF -> DLAI

Dependencies:
- [x] LAPACK
- [x] SCALAPACK
- [x] MKL
- [x] HWLOC
- [x] Fortran

Backends:
- [x] ELPA
- [x] DPLASMA
  - [x] Open an issue about problems with the DPLASMA cmake config file they provide
- [ ] ~HPX_LINALGS -> DLAF~ (this will be a topic for PR #90)
  - [ ] ~Test if a basic code builds (take it from the work in progress branch)~
  - [ ] ~What about HPX testing facilities and arguments? @rasolca~

### CODE REVIEW

**Comment by albestro** [comment]
For what concerns MKL, currently the  check `MKL_NUM_THREADS_UTIL` is missing with the FindMKL.

Are you OK with opening an issue and addressing it separately?

**Comment by albestro** [comment]
For what concerns DPLASMA, they are providing their own cmake find module. I think we should rely on that, so I removed our custom one, but their one at the moment does not work correctly. I will open an issue on their repo about this.

**Comment by albestro** [comment]
I enabled all the warnings we have in DLAF, and there are a lot of things to be fixed. I think it is not worth fixing them in this PR, so I think I will delay the enabling to that specific PR where all of them will be solved.

**Comment by albestro** [comment]
Trying to sum up the multitude of changes.

- CMake has been modernized and cleaned up a bit
- Created two different CMake targets, `DLAI_CXX` and `DLAI_Fortran`
- CMake test functions imported and adapted from DLAF
- Installation of DLAI library added (not extensively tested yet)
- GTest imported as external project
- Build warnings predisposition, not yet enabled (it will be topic for a next PR)
- DPLASMA backend now uses official CMake config-module (https://bitbucket.org/icldistcomp/dplasma/pull-requests/69)
- Started migration from HPXLINALG to DLAF. CMake part should be ready for using the DLAF provided CMake config-module.
- FindELPA and LAPACK/SCALAPACK (and MKL) management has been simplified, it will for sure see changes in the future, but for the moment the target is making it work (we will see if it will requires any fixes with the CI PR #87)

I think it is worth reviewing and merging this PR, and then all refinements will come in smaller dedicated PRs.

**Review by rasolca — APPROVED** [review]

**Pull request merged**
